name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: tgfcfixtures
        path: ~/tgfcfixtures/tgfcfixtures/target/release/tgfxfixtures
    - uses: actions/upload-artifact@v3
      with:
        name: default.template
        path: ~/tgfcfixtures/tgfcfixtures/default.template
    
